name: Build MSI Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset -y

      - name: Build MSI Installer
        run: |
          cd src/main/wix
          candle.exe installer.wxs -out installer.wixobj
          light.exe installer.wixobj -out installer.msi

      - name: Upload MSI Installer
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: src/main/wix/installer.msi

      # SonarCloud analysis step
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: nroduit-github
          token: ${{ secrets.SONAR_TOKEN }}
